# Generated by Django 2.2.13 on 2020-07-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20181007_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'verbose_name': 'reminder', 'verbose_name_plural': 'reminders'},
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateTimeField(verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Document', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
    ]
