language: python

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libpoppler-cpp-dev

sudo: false

matrix:
    include:
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          env: TOXENV=pycodestyle

install:
    - pip install --requirement requirements.txt
    - pip install tox

script: tox -c src/tox.ini
