# Generated by Django 2.0.10 on 2019-06-05 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0022_auto_20181007_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondent', models.CharField(blank=True, db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, db_index=True, max_length=128)),
                ('file_name', models.CharField(max_length=300)),
                ('added', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('processed', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('correspondent', 'title'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.Scan'),
        ),
    ]
