# Generated by Django 2.2.14 on 2020-07-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_auto_20200715_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pages',
            field=models.IntegerField(default=1, editable=False, help_text='Number of pages', verbose_name='pagecount'),
        ),
    ]
