# Generated by Django 2.2.14 on 2020-07-31 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_document_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='documentcreated'),
        ),
    ]
